#!/bin/bash

CC='\e[0m'
R1='\e[31;1m'
G1='\e[32;1m'
Y1='\e[33;1m'

DIR="$( dirname $(readlink -f $0))"
PYTHON='python3'
BRAINFUCK_TUNNEL="$DIR/.brainfuck-tunnel"
BRAINFUCK_TUNNEL_APP="$BRAINFUCK_TUNNEL/app.py"
BRAINFUCK_TUNNEL_APP_PID="$BRAINFUCK_TUNNEL/storage/app.pid"
BRAINFUCK_TUNNEL_APP_LOG="$BRAINFUCK_TUNNEL/storage/app.log"
BRAINFUCK_TUNNEL_ACCOUNT="$BRAINFUCK_TUNNEL/database/account.json"
BRAINFUCK_TUNNEL_DEFAULT_SETTINGS="$BRAINFUCK_TUNNEL/default-settings.py"
BRAINFUCK_TUNNEL_RESET_TO_DEFAULT_SETTINGS="$BRAINFUCK_TUNNEL/reset-to-default-settings.py"

#
#

log()
{
    echo -e "$G1$2$1$CC"
}

logtime()
{
    log "[$( date +%T )] $1" $2
}

createfile()
{
    touch $1 &> /dev/null
}

deletefile()
{
    rm -f $1 &> /dev/null
}

readfile()
{
    createfile $1
    cat $1
}

readjson()
{
    cat $1 | grep "\"$2\": " | awk -F '"' '{print $4}'
}

killpid()
{
    createfile $1
    while read pid; do kill $pid &> /dev/null; done < $1
    deletefile $1
    createfile $1
}

service()
{
    $* &> /dev/null & disown
}

stopscreen()
{
    echo $1 >> $BRAINFUCK_TUNNEL_APP_LOG
}

#
#

help()
{
    log 'Usage: brainfuck [start] [run] [connect] [restart]'
    log '                 [reconnect] [stop] [disconnect]'
    log '                 [reset]'
}

is_running()
{
    if [[ ! -z $(readfile $BRAINFUCK_TUNNEL_APP_PID ) ]]; then running=1; else running=0; fi

    return $running
}

start()
{
    local running;
    local status;

    running=0 && is_running || running=1

    case $running in
        0 )
            deletefile $BRAINFUCK_TUNNEL_APP_LOG
            createfile $BRAINFUCK_TUNNEL_APP_LOG
            service $PYTHON $BRAINFUCK_TUNNEL_APP
            tail -f $BRAINFUCK_TUNNEL_APP_LOG -n 0 | {
                while read line; do
                    if [[ -z "$line" ]]; then
                        echo; continue
                    fi

                    log "$line"

                    status=$( echo "$line" | grep -E '\[[0-9:]{8}\] (Connected|Disconnected)' | awk -F ' ' '{print $2}')

                    if [[ ! -z "$status" ]]; then
                        case $status in
                            'Disconnected' )
                                stop false

                                stopscreen
                                break
                            ;;

                            'Connected' )

                                # configurations iptables and redsocks here

                                stopscreen "[$( date +%T )] Brainfuck running in the background"
                                break
                            ;;
                        esac
                    fi
                done
            }
        ;;

        1 )
            logtime 'Brainfuck is running!' $R1
        ;;
    esac
}

showlog()
{
    local running;

    running=0 && is_running || running=1

    case $running in
        0 )
            logtime "Brainfuck not running!" $R1
        ;;

        1 )
            while read value; do
                log "$value"
            done < $BRAINFUCK_TUNNEL_APP_LOG
        ;;
    esac
}

stop()
{
    local running;

    running=0 && is_running || running=1

    case $running in
        0 )
            if [[ -z $1 ]]; then
                logtime "Brainfuck not running." $R1
            fi
        ;;

        1 )
            if [[ -z $1 ]]; then showlog; fi

            # configurations iptables and redsocks here

            killpid "$BRAINFUCK_TUNNEL_APP_PID"

            if [[ -z $1 ]]; then
                logtime "Brainfuck stopped." $R1
            fi
        ;;
    esac
}

menu()
{
    clear; clear
    log 'Brainfuck Tunnel [Rabbit Version 1.3.190310]'
    log '(c) 2019 Aztec Rabbit.'

    echo
    case $1 in

        'start' | 'run' | 'connect' )
            start
        ;;

        'stop' | 'disconnect' )
            stop
        ;;

        'restart' | 'reconnect' )
            stop false; start
        ;;

        'reset' )
            logtime 'Reseting to default settings'
            $PYTHON $BRAINFUCK_TUNNEL_RESET_TO_DEFAULT_SETTINGS &> /dev/null
            logtime 'Reseting to default settings complete'
        ;;

        'log' | 'status' )
            showlog
        ;;

        'update' )
            cd $DIR; git pull
        ;;

        * )
            help
        ;;

    esac
    echo
}

#
#

$PYTHON $BRAINFUCK_TUNNEL_DEFAULT_SETTINGS &> /dev/null

HOST=$( readjson $BRAINFUCK_TUNNEL_ACCOUNT host )
PORT=$( readjson $BRAINFUCK_TUNNEL_ACCOUNT port )
USERNAME=$( readjson $BRAINFUCK_TUNNEL_ACCOUNT username )
PASSWORD=$( readjson $BRAINFUCK_TUNNEL_ACCOUNT password )
SOCKPORT=$( readjson $BRAINFUCK_TUNNEL_ACCOUNT sockport )

menu $*
